# Generated by Django 2.0 on 2018-01-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180112_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='inviter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_invites', to='myapp.Person'),
            preserve_default=False,
        ),
    ]
